export const DEFAULT_MAX_RETRIES = 2;
export const DEFAULT_TIMEOUT_IN_MS = 60000; // 60 seconds
export const RETRY_RANDOMIZATION_FACTOR = 1.5;
export const SPARK_SDK = 'Spark JS SDK';

export const ENV_VARS = {
  BASE_URL: 'CSPARK_BASE_URL',
  API_KEY: 'CSPARK_API_KEY',
  BEARER_TOKEN: 'CSPARK_BEARER_TOKEN',
  CLIENT_ID: 'CSPARK_CLIENT_ID',
  CLIENT_SECRET: 'CSPARK_CLIENT_SECRET',
  OAUTH_PATH: 'CSPARK_OAUTH_PATH',
} as const;
