name: Build Packages

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore: ['**.md', 'LICENSE', '.nvmrc']
  schedule:
    - cron: '0 0 1 * *' # Run at midnight on the first of every month.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install SDK dependencies
        run: yarn install

      - name: Format codebase
        run: yarn run format

      - name: Analyze codebase
        run: yarn run lint

      - name: Run unit tests
        run: yarn test

      - name: Build SDK package
        run: yarn build

      - name: Persist SDK build
        uses: actions/upload-artifact@v4
        with:
          name: spark-ts-sdk
          path: lib
          retention-days: 1

      - name: Prepare Hybrid Runner build
        run: |
          cd packages/wasm
          yarn install
          yarn test
          yarn build

      - name: Persist Hybrid package
        uses: actions/upload-artifact@v4
        with:
          name: spark-ts-wasm
          path: packages/wasm/lib
          retention-days: 1
