name: CI

on:
  push:
    branches: [dev]
    paths-ignore: ['**.md', 'LICENSE', '.nvmrc']

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node: ['14.15.0', '16.0.0']
        exclude:
          - os: macOS-latest
            node: '14.15.0'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install SDK dependencies
        run: npm install --ignore-scripts

      - name: Run unit tests for SDK
        run: npm test

      - name: Build SDK package
        run: npm run build

      - name: Install Hybrid Runner dependencies
        run: |
          cd packages/wasm
          npm install --ignore-scripts

      - name: Run unit tests for Hybrid
        run: npm test
